<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="FITR_002_IS1_SI" targetNamespace="urn:sap-com:sprx:ep:cust:FITR_002"
    xmlns:p1="urn:sap-com:sprx:ep:cust:FITR_002"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:documentation/>
    <wsp:UsingPolicy wsdl:required="true"/>
    <wsp:Policy wsu:Id="OP_FITR_002_IS1_SI"/>
    <wsdl:types>
        <xsd:schema targetNamespace="urn:sap-com:sprx:ep:cust:FITR_002"
            xmlns="urn:sap-com:sprx:ep:cust:FITR_002"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:element name="FITR_002_IS1_MT" type="FITR_002_IS1_DT"/>
            <xsd:complexType name="FITR_002_IS1_DT">
                <xsd:sequence>
                    <xsd:element name="IT_ER_REQ" minOccurs="0" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="I_ETYPE" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="I_FCURR" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="I_TCURR" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="I_EDATE" type="xsd:string" minOccurs="0"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="FITR_002_IS2_MT" type="FITR_002_IS2_DT"/>
            <xsd:complexType name="FITR_002_IS2_DT">
                <xsd:sequence>
                    <xsd:element name="IT_ER_RETURN" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="KURST" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="FCURR" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="TCURR" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="GDATU" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="UKURS" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="FFACT" type="xsd:string" minOccurs="0"/>
                                <xsd:element name="TFACT" type="xsd:string" minOccurs="0"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="E_MSG" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="E_MSG" type="xsd:string" minOccurs="0"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="FITR_002_IS1_MT">
        <wsdl:documentation/>
        <wsdl:part name="FITR_002_IS1_MT" element="p1:FITR_002_IS1_MT"/>
    </wsdl:message>
    <wsdl:message name="FITR_002_IS2_MT">
        <wsdl:documentation/>
        <wsdl:part name="FITR_002_IS2_MT" element="p1:FITR_002_IS2_MT"/>
    </wsdl:message>
    <wsdl:portType name="FITR_002_IS1_SI">
        <wsdl:documentation/>
        <wsdl:operation name="FITR_002_IS1_SI">
            <wsdl:documentation/>
            <wsp:Policy>
                <wsp:PolicyReference URI="#OP_FITR_002_IS1_SI"/>
            </wsp:Policy>
            <wsdl:input message="p1:FITR_002_IS1_MT"/>
            <wsdl:output message="p1:FITR_002_IS2_MT"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="FITR_002_IS1_SIBinding" type="p1:FITR_002_IS1_SI">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"
            xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
        <wsdl:operation name="FITR_002_IS1_SI">
            <soap:operation soapAction="http://sap.com/xi/WebService/soap1.1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            <wsdl:input>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>