<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SKST_004_OA1_SI" targetNamespace="http://skshieldus.com/SKST_004" xmlns:p1="http://skshieldus.com/SKST_004" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:documentation/>
	<wsp:UsingPolicy wsdl:required="true"/>
	<wsp:Policy wsu:Id="OP_SKST_004_OA1_SI"/>
	<wsdl:types>
		<xsd:schema targetNamespace="http://skshieldus.com/SKST_004" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://skshieldus.com/SKST_004">
			<xsd:element name="SKST_004_OA1_MT" type="SKST_004_OA1_DT"/>
			<xsd:complexType name="SKST_004_OA1_DT">
				<xsd:sequence>
					<xsd:element name="IV_CARRID" type="xsd:string" minOccurs="0"/>
					<xsd:element name="SEND_HEADER" type="xsd:string" minOccurs="0"/>
					<xsd:element name="SEND_PROPERTY" type="xsd:string" minOccurs="0"/>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="SKST_004_OA1_MT">
		<wsdl:documentation/>
		<wsdl:part name="SKST_004_OA1_MT" element="p1:SKST_004_OA1_MT"/>
	</wsdl:message>
	<wsdl:portType name="SKST_004_OA1_SI">
		<wsdl:documentation/>
		<wsdl:operation name="SKST_004_OA1_SI">
			<wsdl:documentation/>
			<wsp:Policy>
				<wsp:PolicyReference URI="#OP_SKST_004_OA1_SI"/>
			</wsp:Policy>
			<wsdl:input message="p1:SKST_004_OA1_MT"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SKST_004_OA1_SIBinding" type="p1:SKST_004_OA1_SI">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
		<wsdl:operation name="SKST_004_OA1_SI">
			<soap:operation soapAction="http://sap.com/xi/WebService/soap1.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
			<wsdl:input>
				<soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>