<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:sap-com:sprx:ep:cust:CEMS_001" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CEMS_001" targetNamespace="urn:sap-com:sprx:ep:cust:CEMS_001">
  
 <wsdl:types>
 
 <!-- 
    레거시 송신 케이스에서는 네임스페이스 삭제하여 사용. ( JSON -> XML 컨버팅시 NS 문제때문에...)
  ERP 수신 side 는  하기와 같은 네임스페이스 적용필요 ( Proxy 생성시 자동 생성됨-> se80 프록시 정보에서 확인 가능 )
    <xsd:schema>
 -->
   <xsd:schema targetNamespace="urn:sap-com:sprx:ep:cust:CEMS_001" xmlns="urn:sap-com:sprx:ep:cust:CEMS_001">
 
<!-- 일괄 변경: 네임스페이스 ( SAP Proxy 송신인 케이스만 적용)
   Sync NS:    urn:sap-com:sprx:ep:cust:CEMS_001
   ASync NS:   http://is.co.kr/Async
 -->
 
<!-- 일괄 변경: I/F ID -->
   <xsd:element name="CEMS_001_RECV_REQ_MT" type="CEMS_001_RECV_REQ_DT"/>   
   <xsd:element name="CEMS_001_RECV_RES_MT" type="CEMS_001_RECV_RES_DT"/> 
   
   
   <xsd:complexType name="CEMS_001_RECV_REQ_DT">
		<xsd:sequence>	
<!-- Request Data type 시작 -->	

					<xsd:element name="ROOT">
						
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="IFCODE" type="IFCODE_DT">
									
								</xsd:element>
								<xsd:element name="DATA">
									
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="LEASETYPE">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="LIFNR">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="HKONT">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="CHACOD">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="BUPER">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="BUPRE">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="MEMO"  minOccurs="0">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="WAERS">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="LEASEDMBTR">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="EMPNO"  minOccurs="0">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="BUKRS">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="CONTRACT_NO">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>

<!-- Request Data type 끝 -->
		</xsd:sequence>
   </xsd:complexType>
   
   
   <xsd:complexType name="CEMS_001_RECV_RES_DT">
    <xsd:sequence>
<!-- Response Data type 시작 -->
					<xsd:element name="ROOT">
						
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="DATA">
									
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="STATUS"  minOccurs="0">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="MSG" minOccurs="0">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="LEASENUM" minOccurs="0">
												
												<xsd:simpleType>
													<xsd:restriction base="xsd:string">
														
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
<!-- Response Data type 끝 -->
    </xsd:sequence>
   </xsd:complexType>
   

<!-- 그외 참조 Data type 시작 --> 
            <!-- 공통 data Type IFCODE_DT  --> 
			<xsd:complexType name="IFCODE_DT">
				
				<xsd:sequence>
					<xsd:element name="GUBUN">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="LANG" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="SDATE" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="STIME" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="USERCD" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="SEARCHKEY1" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="SEARCHKEY2" minOccurs="0">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="CRUD">
						
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
			
<!-- 그외 참조 Data type END -->    
   
   
  </xsd:schema>
 </wsdl:types>
 
 <wsdl:message name="CEMS_001_RECV_REQ_MT">
  <wsdl:part name="CEMS_001_RECV_REQ_MT" element="tns:CEMS_001_RECV_REQ_MT"/>
 </wsdl:message>
  <wsdl:message name="CEMS_001_RECV_RES_MT">
  <wsdl:part name="CEMS_001_RECV_RES_MT" element="tns:CEMS_001_RECV_RES_MT"/>
 </wsdl:message>
 
  
  <wsdl:portType name="CEMS_001">
    <wsdl:operation name="CEMS_001">
      <wsdl:input message="tns:CEMS_001_RECV_REQ_MT"/>
      <wsdl:output message="tns:CEMS_001_RECV_RES_MT"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CEMS_001SOAP" type="tns:CEMS_001">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CEMS_001">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CEMS_001">
    <wsdl:port binding="tns:CEMS_001SOAP" name="CEMS_001SOAP">
      <soap:address location="https://sk-ep/cxf/CEMS_001"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
