<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://skshieldus.com/SKST_008" xmlns:p1="http://skshieldus.com/SKST_008" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://skshieldus.com/SKST_008" xmlns="http://skshieldus.com/SKST_008" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:element name="SKST_008_OA1_MT" type="SKST_008_OA1_DT"/>
            <xsd:complexType name="SKST_008_OA1_DT">
                <xsd:sequence>
                    <xsd:element name="IV_CARRID" type="xsd:string" minOccurs="0"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SKST_008_OA1_MT">
        <wsdl:documentation/>
        <wsdl:part name="SKST_008_OA1_MT" element="p1:SKST_008_OA1_MT">
    </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="SKST_008_OA1_SI">
        <wsdl:documentation/>
        <wsdl:operation name="SKST_008_OA1_SI">
            <wsdl:documentation/>
            <wsdl:input message="p1:SKST_008_OA1_MT">
    </wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SKST_008_OA1_SIBinding" type="p1:SKST_008_OA1_SI">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:Policy>
            <wsp:PolicyReference URI="#BN__binding"/>
        </wsp:Policy>
        <wsdl:operation name="SKST_008_OA1_SI">
            <soap:operation soapAction="http://sap.com/xi/WebService/soap1.1"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SKST_008_OA1_SIService">
        <wsdl:port name="HTTP_Port" binding="p1:SKST_008_OA1_SIBinding">
            <soap:address location="https://skshieldus.com/cxf/SKST_008_OA1_SI"/>
        </wsdl:port>
    </wsdl:service>
    <wsp:UsingPolicy required="true"/>
    <wsp:Policy wsu:Id="BN__binding">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <wsp:ExactlyOne>
                                            <sp:HttpBasicAuthentication/>
                                            <sp:RequireClientCertificate/>
                                        </wsp:ExactlyOne>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <wsp:ExactlyOne>
                                    <sp:Basic256/>
                                    <sp:Basic192/>
                                    <sp:Basic128/>
                                    <sp:TripleDes/>
                                    <sp:Basic256Rsa15/>
                                    <sp:Basic192Rsa15/>
                                    <sp:Basic128Rsa15/>
                                    <sp:TripleDesRsa15/>
                                    <sp:Basic256Sha256/>
                                    <sp:Basic192Sha256/>
                                    <sp:Basic128Sha256/>
                                    <sp:TripleDesSha256/>
                                    <sp:Basic256Sha256Rsa15/>
                                    <sp:Basic192Sha256Rsa15/>
                                    <sp:Basic128Sha256Rsa15/>
                                    <sp:TripleDesSha256Rsa15/>
                                </wsp:ExactlyOne>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                    </wsp:Policy>
                </sp:TransportBinding>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
